framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
            loco:
                dsn: '%env(LOCO_DSN)%'
                domain: ['accueil']
                locales: ['en', 'fr', 'es']
